---
- hosts: perfectmediaserver
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: ironicbadger.proxmox_nag_removal
    - role: geerlingguy.docker
    - role: grog.package
    - role: ironicbadger.hddtemp
    - role: ironicbadger.bash_aliases
    - role: perfectmediaserver
    - role: ironicbadger.docker_compose_generator
      tags: compose
    - role: ktz-traefik
      tags: compose
    # - role: artis3n.tailscale
